0-world_wide_web

diff --git a/0x10-https_ssl/0-world_wide_web b/0x10-https_ssl/0-world_wide_web
--- a/0x10-https_ssl/0-world_wide_web
+++ b/0x10-https_ssl/0-world_wide_web
@@ -1,19 +1,41 @@
 #!/usr/bin/env bash
 # Autor : SAID LAMGHARI
 
+# Fonction pour rechercher un sous-domaine
 function lookup_subdomain() {
     dig "$1.$2" +short | awk 'BEGIN { FS = " " } { print "The subdomain " $1 " is a " $3 " record and points to " $4 }'
 }
 
-if [ -z "$1" ]; then
+# Vérifier si le nombre d'arguments est correct
+if [ $# -lt 1 ] || [ $# -gt 2 ]; then
     echo "Usage: $0 domain [subdomain]"
     exit 1
 fi
-if [ -z "$2" ]; then
-    lookup_subdomain www "$1"
-    lookup_subdomain lb-01 "$1"
-    lookup_subdomain web-01 "$1"
-    lookup_subdomain web-02 "$1"
+
+# Récupérer le nom de domaine et le sous-domaine (facultatif)
+domain="$1"
+subdomain="${2:-}"
+
+# Vérifier si le nom de domaine est vide
+if [ -z "$domain" ]; then
+    echo "Error: Domain name cannot be empty."
+    exit 1
+fi
+
+# Vérifier si le sous-domaine est vide
+if [ -n "$subdomain" ] && [ -z "$subdomain" ]; then
+    echo "Error: Subdomain cannot be empty."
+    exit 1
+fi
+
+# Rechercher les informations sur le sous-domaine
+if [ -z "$subdomain" ]; then
+    # Rechercher les informations sur les sous-domaines www, lb-01, web-01 et web-02
+    lookup_subdomain www "$domain"
+    lookup_subdomain lb-01 "$domain"
+    lookup_subdomain web-01 "$domain"
+    lookup_subdomain web-02 "$domain"
 else
-    lookup_subdomain "$2" "$1"
+    # Rechercher les informations sur le sous-domaine spécifié
+    lookup_subdomain "$subdomain" "$domain"
 fi
